const products = [
  {id:1,name:'Siena Lounge Chair',category:'living',price:18500,image:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=700&q=80',tag:'Best seller'},
  {id:2,name:'Everyday Dinner Set',category:'kitchen',price:6200,image:'https://images.unsplash.com/photo-1603199506016-b9a594b593c0?auto=format&fit=crop&w=700&q=80',tag:'New'},
  {id:3,name:'Soft Haven Throw',category:'bedroom',price:3900,image:'https://images.unsplash.com/photo-1583845112203-454c0f8f2c12?auto=format&fit=crop&w=700&q=80',tag:''},
  {id:4,name:'Olea Table Lamp',category:'living',price:7400,image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=700&q=80',tag:'New'},
  {id:5,name:'Woven Storage Basket',category:'living',price:2850,image:'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=700&q=80',tag:''},
  {id:6,name:'Stoneware Mug Set',category:'kitchen',price:3200,image:'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=700&q=80',tag:''},
  {id:7,name:'Linen Duvet Cover',category:'bedroom',price:9600,image:'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=700&q=80',tag:'Popular'},
  {id:8,name:'Acacia Serving Board',category:'kitchen',price:2400,image:'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?auto=format&fit=crop&w=700&q=80',tag:''},
  {id:9,name:'Cloud Cotton Towel Set',category:'bath',price:4800,image:'https://images.unsplash.com/photo-1584622781867-6c4cbb8c7a58?auto=format&fit=crop&w=700&q=80',tag:'New'},
  {id:10,name:'Bamboo Laundry Basket',category:'bath',price:5600,image:'https://images.unsplash.com/photo-1583845112203-454c0f8f2c12?auto=format&fit=crop&w=700&q=80',tag:''},
  {id:11,name:'Stackable Storage Set',category:'storage',price:4300,image:'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=700&q=80',tag:'Popular'},
  {id:12,name:'Natural Cleaning Kit',category:'storage',price:2950,image:'https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=700&q=80',tag:'New'},
  {id:13,name:'Marlow Side Table',category:'living',price:12800,image:'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=700&q=80',tag:''},
  {id:14,name:'Rattan Floor Basket',category:'living',price:4200,image:'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=700&q=80',tag:'New'},
  {id:15,name:'Olive Cushion Cover',category:'living',price:1850,image:'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=700&q=80',tag:''},
  {id:16,name:'Glass Food Storage Set',category:'kitchen',price:4500,image:'https://images.unsplash.com/photo-1583947582886-f40ec95dd752?auto=format&fit=crop&w=700&q=80',tag:'Popular'},
  {id:17,name:'Everyday Prep Knife',category:'kitchen',price:1950,image:'https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&w=700&q=80',tag:''},
  {id:18,name:'Woven Table Runner',category:'kitchen',price:2200,image:'https://images.unsplash.com/photo-1603199506016-b9a594b593c0?auto=format&fit=crop&w=700&q=80',tag:''},
  {id:19,name:'Washed Cotton Sheet Set',category:'bedroom',price:8300,image:'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=700&q=80',tag:'Best seller'},
  {id:20,name:'Arlo Bedside Lamp',category:'bedroom',price:6800,image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=700&q=80',tag:''},
  {id:21,name:'Linen Euro Pillowcase',category:'bedroom',price:2400,image:'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=700&q=80',tag:''},
  {id:22,name:'Stone Soap Dispenser',category:'bath',price:1700,image:'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=700&q=80',tag:''},
  {id:23,name:'Teak Shower Caddy',category:'bath',price:5100,image:'https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=700&q=80',tag:'New'},
  {id:24,name:'Spa Cotton Bath Mat',category:'bath',price:2600,image:'https://images.unsplash.com/photo-1584622781867-6c4cbb8c7a58?auto=format&fit=crop&w=700&q=80',tag:''},
  {id:25,name:'Underbed Storage Box',category:'storage',price:3600,image:'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=700&q=80',tag:''},
  {id:26,name:'Foldable Utility Basket',category:'storage',price:2750,image:'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=700&q=80',tag:'Popular'},
  {id:27,name:'Microfibre Cloth Set',category:'storage',price:1250,image:'https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=700&q=80',tag:''}
];
let cart=[]; const fmt=n=>`KSh ${n.toLocaleString()}`; const grid=document.querySelector('#product-grid');
function renderProducts(filter='all'){grid.innerHTML=products.filter(p=>filter==='all'||p.category===filter).map(p=>`<article class="product"><div class="product-image"><img src="${p.image}" alt="${p.name}">${p.tag?`<span class="label">${p.tag}</span>`:''}<button class="add" data-id="${p.id}" aria-label="Add ${p.name} to bag">+</button></div><div class="product-info"><div><h3>${p.name}</h3><p>${p.category[0].toUpperCase()+p.category.slice(1)}</p></div><span class="price">${fmt(p.price)}</span></div></article>`).join('')}
function renderCart(){const items=document.querySelector('.cart-items'),empty=document.querySelector('.empty-cart'),footer=document.querySelector('.cart-footer');items.innerHTML=cart.map(item=>`<div class="cart-item"><img src="${item.image}" alt=""><div><h3>${item.name}</h3><p>${fmt(item.price)}</p></div><button class="remove" data-id="${item.id}">Remove</button></div>`).join('');const total=cart.reduce((sum,p)=>sum+p.price,0);document.querySelectorAll('.cart-count').forEach(e=>e.textContent=cart.length);document.querySelector('.subtotal').textContent=fmt(total);empty.style.display=cart.length?'none':'block';footer.style.display=cart.length?'block':'none'}
function toast(message){const t=document.querySelector('.toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
grid.addEventListener('click',e=>{const id=Number(e.target.dataset.id);if(!id)return;const product=products.find(p=>p.id===id);cart.push(product);renderCart();toast(`${product.name} added to your bag`)})
document.querySelector('.cart-items').addEventListener('click',e=>{const id=Number(e.target.dataset.id);if(!id)return;cart.splice(cart.findIndex(p=>p.id===id),1);renderCart()})
document.querySelectorAll('.filters button').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.filters .active').classList.remove('active');button.classList.add('active');renderProducts(button.dataset.filter)}));
document.querySelectorAll('.shop-menu a').forEach(link=>link.addEventListener('click',()=>{const filter=link.dataset.category;document.querySelector('.filters .active').classList.remove('active');document.querySelector('.filters [data-filter="'+filter+'"]').classList.add('active');renderProducts(filter)}));
const dropdownToggle=document.querySelector('.nav-dropdown-toggle'),dropdownMenu=document.querySelector('.nav-dropdown-menu');
dropdownToggle.addEventListener('click',()=>{const open=dropdownMenu.classList.toggle('open');dropdownToggle.setAttribute('aria-expanded',open)});
document.querySelectorAll('.nav-dropdown-menu a').forEach(link=>link.addEventListener('click',()=>{const filter=link.dataset.category;document.querySelector('.filters .active').classList.remove('active');document.querySelector('.filters [data-filter="'+filter+'"]').classList.add('active');renderProducts(filter);dropdownMenu.classList.remove('open');dropdownToggle.setAttribute('aria-expanded','false')}));
document.addEventListener('click',event=>{if(!event.target.closest('.nav-dropdown')){dropdownMenu.classList.remove('open');dropdownToggle.setAttribute('aria-expanded','false')}});
const panel=document.querySelector('.cart-panel'),overlay=document.querySelector('.overlay');function toggleCart(open){panel.classList.toggle('open',open);overlay.classList.toggle('open',open);panel.setAttribute('aria-hidden',!open)}document.querySelector('.cart-button').addEventListener('click',()=>toggleCart(true));document.querySelector('.close-cart').addEventListener('click',()=>toggleCart(false));overlay.addEventListener('click',()=>toggleCart(false));
document.querySelector('.checkout').addEventListener('click',()=>toast('Checkout will be connected when payments are set up.'));
document.querySelector('.search-toggle').addEventListener('click',()=>{document.querySelector('#shop').scrollIntoView();document.querySelector('.filters button').focus()});document.querySelector('#year').textContent=new Date().getFullYear();renderProducts();renderCart();
